config/routes.rb
Rails.application.routes.draw do

	resources :admin, only: :index do
		post :add, on: :collection
	end

	resources :maxims do
		get :admin, on: :collection
		get :preview, on: :member
		get :random, on: :collection
	end

	resources :notes do
		get :admin, on: :collection
	end

	resources :songs do
		get :admin, on: :collection
		get :preview, on: :member
	end

	resources :tasks do
		get :admin, on: :collection
	end

	devise_scope :user do
		get '/login' => 'sessions#new', as: 'login'
		get '/logout' => 'sessions#destroy', as: 'logout'
	end
	devise_for :users, :controllers => { :omniauth_callbacks => 'oauth', :sessions => 'sessions' }

	mount SwellMedia::Engine, :at => '/'

end

app/models/task.rb
class Task < ActiveRecord::Base

	attr_accessor	:parent_id # for building parent associations in form_for

	enum status: { 'pending' => 0, 'active' => 1, 'completed' => 2, 'confirmed' => 3, 'trash' => 4 }
	enum availability: { 'just_me' => 0, 'team' => 1, 'anyone' => 2 }

	belongs_to	:assigned_to, class_name: 'User'
	belongs_to 	:requested_by, class_name: 'User'
	belongs_to	:category

	has_many	:assets
	has_many	:timers

	extend FriendlyId
	friendly_id :name, :use => :slugged

	acts_as_nested_set

	acts_as_taggable_on	:tags

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	before_filter :authenticate_user!
	before_filter :get_task, except: [ :admin, :create, :index ]

	def admin
		authorize( Task )
		sort_by = params[:sort_by] || 'due_at'
		sort_dir = params[:sort_dir] || 'desc'

		@tasks = Task.roots.order( "#{sort_by} #{sort_dir}" )

		if params[:status].present? && params[:status] != 'all'
			@tasks = eval "@tasks.#{params[:status]}"
		end

		@tasks = @tasks.page( params[:page] )

		render layout: 'admin'
	end

	def create
		@task = Task.new( task_params )

		@task.assigned_to_id ||= current_user
		@task.requested_by_id ||= current_user

		if @task.save
			if parent_task = Task.find_by( id: params[:task][:parent_id] )
				@task.move_to_child_of( parent_task )
			end

			set_flash "Task created"
		else
			set_flash "Task could not be saved.", :error, @task
		end

		redirect_to edit_task_path( @task )
	end

	def destroy
		@task.trash!
		redirect_to :back
	end

	def edit
		
		render layout: 'admin'
	end

	def update
		authorize( @task )
		@task.attributes = task_params
		@task.completed_at = Time.zone.now if @task.completed?
		@task.confirmed_at = Time.zone.now if @task.confirmed?

		if @task.save
			set_flash 'Task Updated'
			redirect_to edit_task_path( id: @task.id )
		else
			set_flash 'Task could not be Updated', :error, @task
			render :edit
		end
	end


	private

		def get_task
			@task = Task.friendly.find( params[:id] )
		end

		def task_params
			params.require( :task ).permit( :assigned_to_id, :requested_by_id, :name, :description, :content, :status, :due_at, :availability, :priority, :remind_time, :tag_list, :category_id )
		end
end

app/views/tasks/_new_modal.html.haml
#new_task.modal.fade
	.modal-dialog
		.modal-content
			.modal-header
				%button.close{ type: :button, 'data-dismiss' => 'modal', 'aria-hidden' => 'true' }
					&times;
				%h4.modal-title
					New Task
			= form_for Task.new, url: main_app.tasks_path do |f|
				= f.hidden_field :parent_id, value: args[:parent_id]
				.modal-body
					= f.label :name
					= f.text_field :name, class: 'form-control'
				.modal-footer
					%button.btn.btn-default{ type: :button, 'data-dismiss' => 'modal' }
						Close
					= f.submit 'Create', class: 'btn btn-primary'

app/views/tasks/admin.html.haml
.container-fluid
	.row
		.col-xs-10
			%ul.breadcrumb
				%li
					= link_to 'Admin', admin_index_path
				%li
					%strong
						Tasks
		.col-xs-2
			%a.btn.btn-success.btn-rad{ data: { toggle: :modal, target: '#new_task' } }
				%i.fa.fa-plus-square
				New
	.row
		.col-xs-6
			= raw paginate @tasks
		-#.col-xs-6
			= form_tag admin_tasks_path, method: :get, class: 'pull-right form-inline' do
				= select_tag :status, options_from_collection_for_select( SwellMedia::Article.statuses, :first, :first, params[:status] ), { prompt: "-- All --", class: 'form-control' }
				= text_field_tag :q, params[:q], class: 'form-control'
				= submit_tag 'Search', class: 'btn btn-primary'
				= link_to 'Clear', admin_articles_path, class: 'btn btn-default btn-xs'

	.row
		.col-xs-12
			%table.table
				%thead
					%th
					%th
						%a{ href: admin_tasks_path( sort_by: 'name', sort_dir: 'asc' ) }
							%i.fa.fa-arrow-up
						%a{ href: admin_tasks_path( sort_by: 'name', sort_dir: 'desc' ) }
							%i.fa.fa-arrow-down
					%th
						Due
						%a{ href: admin_tasks_path( sort_by: 'due_at', sort_dir: 'asc' ) }
							%i.fa.fa-arrow-up
						%a{ href: admin_tasks_path( sort_by: 'due_at', sort_dir: 'desc' ) }
							%i.fa.fa-arrow-down
					%th
						Priority
						%a{ href: admin_tasks_path( sort_by: 'priority', sort_dir: 'asc' ) }
							%i.fa.fa-arrow-up
						%a{ href: admin_tasks_path( sort_by: 'priority', sort_dir: 'desc' ) }
							%i.fa.fa-arrow-down
					%th Status
					%th
				%tbody
					- @tasks.each do |task|
						%tr
							%td
								= link_to task.name, edit_task_path( task.id )
							%td
								= task.due_at.to_s
							%td
								= task.priority
							%td
								.badge{ class: task.status }
									= task.status
							%td
								.btn-group
									%button.btn.btn-mini.btn-default.dropdown-toggle{ data: { toggle: :dropdown } }
										%i.fa.fa-cog
										%b.caret
									%ul.dropdown-menu
										%li
											%a{ href: edit_task_path( task ) }
												%i.fa.fa-pencil
												Edit
										%li.divider
										%li
											%a{ href: task_path( task ), data: { method: 'delete', confirm: 'Are you sure?' } }
												%i.fa.fa-trash-o
												Delete!




= render 'new_modal', args: {}

app/views/tasks/edit.html.haml
.container-fluid
	.row
		.col-xs-10
			%ul.breadcrumb
				%li
					= link_to 'Admin', admin_index_path
				%li
					= link_to 'Tasks', admin_tasks_path
				%li
					%strong
						Edit
						= @task.name
		.col-xs-2
			%a.btn.btn-success.btn-rad{ data: { toggle: :modal, target: '#new_task' } }
				%i.fa.fa-plus-square
				Add Sub
	
	= form_for @task do |f|
	
		.row
			.col-xs-8
				.form-group
					= f.text_field :name, class: 'form-control input-lg'

				.form-group
					= f.text_area :content, class: 'form-control editor-small', rows: 8

				- @task.children.each do |task|
					= task.name
					mark complete


			.col-xs-4
				.well
					.form-group
						= f.label :due_at
						= f.text_field :due_at, value: @task.due_at.try( :strftime, "%d %B, %Y %H:%M" ), class: 'form-control datepicker'
					.form-group
						= f.label :priority
						= f.text_field :priority, class: 'form-control'
					.form-group
						= f.label :status
						= f.collection_select :status, Task.statuses, :first, :first, {}, class: 'form-control'
					.form-group
						= f.label :tag_list, 'Tags:'
						= f.text_field :tag_list, placeholder: 'Separate tags with commas', class: 'form-control'
					.form-group
						= f.submit 'Update', class: 'btn btn-primary'


= render 'new_modal', args: { parent_id: @task.id }